### ISSUE TITLE
Compiler warnings on strict aliasing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [richgel999/miniz#27]
```
What steps will reproduce the problem?
1. gcc -Wall -Werror -O2 miniz.c
2.
3.

What is the expected output? What do you see instead?
Expected output: Compiler errors due to no main().
Actual output:
Compiler errors due to type punning.
miniz.c: In function ‘tdefl_find_match’:
miniz.c:2270:3: error: dereferencing type-punned pointer will break 
strict-aliasing rules [-Werror=strict-aliasing]
miniz.c:2282:7: error: dereferencing type-punned pointer will break 
strict-aliasing rules [-Werror=strict-aliasing]
miniz.c:2282:7: error: dereferencing type-punned pointer will break 
strict-aliasing rules [-Werror=strict-aliasing]
miniz.c:2282:7: error: dereferencing type-punned pointer will break 
strict-aliasing rules [-Werror=strict-aliasing]
miniz.c:2294:7: error: dereferencing type-punned pointer will break 
strict-aliasing rules [-Werror=strict-aliasing]
miniz.c: In function ‘tdefl_compress_fast’:
miniz.c:2367:7: error: dereferencing type-punned pointer will break 
strict-aliasing rules [-Werror=strict-aliasing]

What version of the product are you using? On what operating system?
9.1.15, all MINIZ_NO_* enabled. Linux Mint 15, AMD64, GCC 4.7.3-1ubuntu1.

Please provide any additional information below.
Disabling warnings, optimization, or both, makes this go away.

```

Original issue reported on code.google.com by `blub...@gmail.com` on 24 Nov 2013 at 5:02

**Comment by uroni** [comment]
This should be fixed now

**Comment by janisozaur** [comment]
There are still errors when compiling with `-fstrict-aliasing`:

```
miniz.c: In function ‘tdefl_find_match’:
miniz.c:1348:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     mz_uint16 c01 = TDEFL_READ_UNALIGNED_WORD(&d->m_dict[pos + match_len - 1]), s01 = TDEFL_READ_UNALIGNED_WORD(s);
     ^~~~~~~~~
miniz.c:1365:13: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
             TDEFL_PROBE;
             ^~~~~~~~~~~
miniz.c:1366:13: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
             TDEFL_PROBE;
             ^~~~~~~~~~~
miniz.c:1367:13: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
             TDEFL_PROBE;
             ^~~~~~~~~~~
miniz.c:1391:13: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
             c01 = TDEFL_READ_UNALIGNED_WORD(&d->m_dict[pos + match_len - 1]);
             ^~~
miniz.c: In function ‘mz_zip_validate_file’:
miniz.c:4935:9: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         has_id = (MZ_READ_LE32(descriptor_buf) == MZ_ZIP_DATA_DESCRIPTOR_ID);
         ^~~~~~
```

**Comment by janisozaur** [comment]
This can be alleviated by disabling the broken `MINIZ_USE_UNALIGNED_LOADS_AND_STORES` option in the config until a proper fix is in place.

**Comment by huyuguang** [comment]
The issue still does not solve.
So what should I do? Disable the warning in code or I must compile with -fno-strict-aliasing?

**Comment by uroni** [comment]
Ok, sorry. Either set MINIZ_USE_UNALIGNED_LOADS_AND_STORES to zero (less performance on x86/x64), set -fno-strict-aliasing or ignore the warning. The warning should be a false positive.

**Comment by huyuguang** [comment]
Thanks for reply.
So it safe to disable the warning.
